version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./configs:/app/configs
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
